### ISSUE TITLE
error: conflicting types for 'prlimit' & error: static declaration of 'unshare'/'setns' follows non-static declaration

### ISSUE THREAD

**Issue by AwlsomeAlex** [karelzak/util-linux#933]
Hello, I am currently trying to compile util-linux 2.34 and I get the following errors:

`sys-utils/prlimit.c:146:12: error: conflicting types for 'prlimit'`

`./include/namespace.h:34:19: error: static declaration of 'unshare' follows non-static declaration`

`./include/namespace.h:41:19: error: static declaration of 'setns' follows non-static declaration`

The output of make and config can be found [here](https://pastebin.com/4HCCpCqw). This is using an inhouse cross compiler built with Linux Kernel 5.4.11, Glibc 2.30, GCC 9.2.0, Binutils 2.33.1. The compile variables for those packages can be found [here](https://github.com/AwlsomeAlex/stelalinux/tree/master/toolchain/packages), the compile variables for util-linux can be found [here](https://github.com/AwlsomeAlex/stelalinux/blob/master/packages/util-linux/StelaKonstrui).

**Comment by karelzak** [comment]
It seems ./confiugure does not check on the place where gcc look for include files. 

For example:
```
configure:
  checking for syscall prlimit64... SYS_prlimit64
  checking for prlimit... no
```
... so AC_CHECK_FUNCS([prlimit]) does not found the function, but:
```
/home/awlsomealex/Git/stelalinux/toolchain/final/root/usr/include/bits/resource.h:203:12: note: previous declaration of 'prlimit' was here
  203 | extern int prlimit (__pid_t __pid, enum __rlimit_resource __resource,
```

Maybe you can try to call ./configure with the same CFLAGS and LDFLAG like later used for 'make'.

**Comment by AwlsomeAlex** [comment]
I don't use CFLAGS or LDFLAGS for make, I only pass '-j (job number)'. Those flags set for configure are:`LDFLAGS="-L$WRK_DIR/ncurses/ncurses.fs/usr/lib -L$WRK_DIR/zlib/zlib.fs/usr/include" \
    CPPFLAGS="-I$WRK_DIR/ncurses/ncurses.fs/usr/include -I$WRK_DIR/zlib/zlib.fs/usr/include" \
    CFLAGS="$CFLAGS" ./configure \`

Where `CFLAGS="-Os -s -fomit-frame-pointer -pipe"`

**Comment by KnifeOnlyI** [comment]
Hello, I come here because I have the same problem.

I use this command to configure the compilation :

`./configure --prefix=/tools                \
            --without-python               \
            --disable-makeinstall-chown    \
            --without-systemdsystemunitdir \
            --without-ncurses              \
            PKG_CONFIG=""`

And the results is here : https://pastebin.com/ziFRzm5c

I don't think it is a bug. But I don't find the problem...

Thanks for the help.

**Comment by karelzak** [comment]
Maybe we need for prlimit(), unshare(), and setns() the same way we use already for fallocate in condigure.in. It means do not use AC_CHECK_FUNCS(), but directly try compile test.

Please, try:
```diff
diff --git a/configure.ac b/configure.ac
index 8f50e8102..c29c54247 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1404,7 +1404,22 @@ UL_REQUIRES_LINUX([unshare])
 UL_REQUIRES_SYSCALL_CHECK([unshare], [UL_CHECK_SYSCALL([unshare])])
 UL_REQUIRES_HAVE([unshare], [linux_capability_h], [linux/capability.h header file])
 AM_CONDITIONAL([BUILD_UNSHARE], [test "x$build_unshare" = xyes])
-AC_CHECK_FUNCS([unshare])
+AS_IF([test "x$build_unshare" = xyes], [
+  AC_MSG_CHECKING([for valid unshare() function])
+  AC_LINK_IFELSE([AC_LANG_PROGRAM([[
+#include <sched.h>
+]],[[
+   long ret;
+   ret = unshare(0);
+   if (ret != 0) {
+      return 1;
+   }
+   ]])],[
+  AC_MSG_RESULT([yes])
+  AC_DEFINE([HAVE_UNSHARE], [1], [Have valid unshare() function])],[
+  AC_MSG_RESULT([no])])
+])
+
 
 AC_ARG_ENABLE([nsenter],
   AS_HELP_STRING([--disable-nsenter], [do not build nsenter]),
@@ -1414,7 +1429,22 @@ UL_BUILD_INIT([nsenter])
 UL_REQUIRES_LINUX([nsenter])
 UL_REQUIRES_HAVE([nsenter], [setns_syscall], [setns syscall])
 AM_CONDITIONAL([BUILD_NSENTER], [test "x$build_nsenter" = xyes])
-AC_CHECK_FUNCS([setns])
+AS_IF([test "x$build_nsenter" = xyes], [
+  AC_MSG_CHECKING([for valid setns() function])
+  AC_LINK_IFELSE([AC_LANG_PROGRAM([[
+#include <sched.h>
+#include <errno.h>
+]],[[
+   long ret;
+   ret = setns(0, 0);
+   if (ret != EINVAL && ret != EBADF && ret != EPERM) {
+      return 1;
+   }
+   ]])],[
+  AC_MSG_RESULT([yes])
+  AC_DEFINE([HAVE_SETNS], [1], [Have valid setns() function])],[
+  AC_MSG_RESULT([no])])
+])
 
 
 AC_ARG_WITH([cap_ng],
@@ -1707,10 +1737,25 @@ UL_REQUIRES_BUILD([prlimit], [libsmartcols])
 UL_REQUIRES_SYSCALL_CHECK([prlimit], [UL_CHECK_SYSCALL([prlimit64])], [prlimit64])
 AM_CONDITIONAL([BUILD_PRLIMIT], [test "x$build_prlimit" = xyes])
 AS_IF([test "x$build_prlimit" = xyes], [
-  AC_CHECK_FUNCS([prlimit])
+  AC_MSG_CHECKING([for valid prlimit() function])
+  AC_LINK_IFELSE([AC_LANG_PROGRAM([[
+  #include <stdio.h>
+  #include <sys/time.h>
+  #include <sys/resource.h>
+]],[[
+   long ret;
+   ret = prlimit(0, 0, NULL, NULL);
+   if (ret != 0) {
+      return 1;
+   }
+   ]])],[
+  AC_MSG_RESULT([yes])
+  AC_DEFINE([HAVE_PRLIMIT], [1], [Have valid prlimit() function])],[
+  AC_MSG_RESULT([no])])
 ])
 
 
+
 UL_BUILD_INIT([lslocks], [check])
 UL_REQUIRES_LINUX([lslocks])
 UL_REQUIRES_BUILD([lslocks], [libmount])
```

The patch is against the current git tree (master branch).

**Comment by feishengfei** [comment]
I can reproduce this issue (even with AC_CHECK_FUNCS replaced by @karelzak 's suggection on configure.ac) after update util-linux from 2.25.2 into 2.35.1 in  openwrt(chaos_calmer) to v2.35.1(glibc 2.21)

Here is the log.
https://pastebin.com/U5FCuJR4

I update the version of util-linux to fix the issue caused by  librt & libpthread dependence.

**Comment by karelzak** [comment]
> I can reproduce this issue (even with AC_CHECK_FUNCS replaced by @karelzak 's suggection on configure.ac) after update util-linux from 2.25.2 into 2.35.1 in openwrt(chaos_calmer) to v2.35.1(glibc 2.21)
> 
> Here is the log.
> https://pastebin.com/U5FCuJR4

Can you also provide the file `config.log` where is how your ./configure tries to compile the test for unshare (etc.)?

**Comment by feishengfei** [comment]
> > I can reproduce this issue (even with AC_CHECK_FUNCS replaced by @karelzak 's suggection on configure.ac) after update util-linux from 2.25.2 into 2.35.1 in openwrt(chaos_calmer) to v2.35.1(glibc 2.21)
> > Here is the log.
> > https://pastebin.com/U5FCuJR4
> 
> Can you also provide the file `config.log` where is how your ./configure tries to compile the test for unshare (etc.)?

patch:
https://pastebin.com/TcsABFHL

partial config.log:
https://pastebin.com/VZwHiSu4   check on unshare()
https://pastebin.com/mrgzpHvr     check on setns()
https://pastebin.com/qgt4Fvcx     check on prlimit64()
https://pastebin.com/g53YFt52    check for prlimit()

I think I got the key point, the configure fail because toolchain issue first. For glibc 2.21, we should explicitly depends on '-lpthread' when '-lrt' appear in TARGET_LDFLAGS. 
...

**Comment by thesamesam** [comment]
Downstream in Gentoo, we [hit](https://bugs.gentoo.org/801403) this when buildilng util-linux without libxcrypt available for 32 bit (multilib).

It ended up being fixed by both https://github.com/karelzak/util-linux/commit/637cc045ee464909c261d6fa16c71ed15cd455e3 and https://github.com/karelzak/util-linux/commit/75cba8d5cdb2a0e84c23de26007feac977837a6f.

It's interesting that the same failure seems to have appeared in the past with configure-checks-gone-wrong.

**Comment by billasurendra** [comment]
Hi Everyone,

I am trying to compile util-linux-2.36 on my RISC-V OS, but it is giving an error. Can anyone please help me out?
Error:

sys-utils/prlimit.c:146:12: error: conflicting types for 'prlimit'
 extern int prlimit(pid_t p, int resource,
            ^~~~~~~
In file included from /usr/include/sys/resource.h:24:0,
                 from sys-utils/prlimit.c:28:
/usr/include/bits/resource.h:203:12: note: previous declaration of 'prlimit' was here
 extern int prlimit (__pid_t __pid, enum __rlimit_resource __resource,
            ^~~~~~~
make[2]: *** [Makefile:11570: sys-utils/prlimit-prlimit.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/util-linux-2.36.2'
make[1]: *** [Makefile:13799: all-recursive] Error 1
make[1]: Leaving directory '/home/util-linux-2.


Thanks
Billa
