### ISSUE TITLE
Build failure after 0f23e4c

### ISSUE THREAD

**Issue by asavah** [karelzak/util-linux#1063]
After commit 0f23e4c was merged build is failing if blkid/blkid.h is not already present in /usr/include.

```
sys-utils/blkdiscard.c:40:10: fatal error: blkid/blkid.h: No such file or directory
   40 | #include <blkid/blkid.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by karelzak** [comment]
On Fri, Jun 19, 2020 at 05:43:07AM -0700, asavah wrote:
> After commit 0f23e4c was merged build is failing if blkid/blkid.h is not already present in /usr/include.
> 
> ```
> sys-utils/blkdiscard.c:40:10: fatal error: blkid/blkid.h: No such file or directory
>    40 | #include <blkid/blkid.h>
>       |          ^~~~~~~~~~~~~~~
> compilation terminated.
> ```

Fixed. Thanks for your report.

    Karel

-- 
 Karel Zak  <kzak@redhat.com>
 http://karelzak.blogspot.com
